version: 2

builds:
  - ldflags:
      - -X github.com/omarkohl/jip/cmd.Version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  use: github-native
